name: "Victron BLE to MQTT"
description: "Forward available Victron BLE data to MQTT"
url: "https://github.com/AverageJoe89/joes-ha-addons/tree/main/victron-ble-mqtt"
version: "1.0.1"
slug: "victron_ble2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

host_network: true
host_dbus: true

privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/bus/usb
  - /var/run/dbus
volumes:
  - /run/dbus:/run/dbus:ro

schema:
  mqtt_server: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  mqtt_publish_throttle: int
  mqtt_config_publish_throttle: int
  victron_secrets:
    - str

options:
  mqtt_server: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_publish_throttle: 5
  mqtt_config_publish_throttle: 20
  victron_secrets:
    - "secret1"

image: "ghcr.io/averagejoe89/hassio-victron-ble2mqtt-{arch}"